accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_pk>/', views.user_detail, name="user_detail"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name="delete"),
]

motube/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', views.index),
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name="detail"),
    path('<int:movie_pk>/review/', views.create_review, name="create_review"),
    path('<int:movie_pk>/review/delete/<int:review_pk>/', views.delete_review, name="delete_review"),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/score/<int:score>/', views.create_score, name='create_score'),
    path('search/', views.search, name='search'),
]

motube/templates/__nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a id="home" class="navbar-brand" href="{% url 'movies:index' %}">Motube</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movies:index' %}">홈</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:delete' %}">회원탈퇴</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:user_detail' user.pk %}">내 영화</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'movies:search' %}">
      <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<style>
  a {
    font-family: 'Nanum Gothic Coding', monospace;
  }
  #home {
    font-family: 'Calistoga', cursive;
  }
</style>

motube/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Motube</title>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>
<link href="https://fonts.googleapis.com/css?family=Jua&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Jua|Nanum+Gothic+Coding&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Calistoga|Jua|Nanum+Gothic+Coding&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Black+Han+Sans&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|Noto+Serif+KR&display=swap" rel="stylesheet">
<style>
  body {
    background-color: #282828;
  }
</style>
<body>
  {% include '__nav.html' %}
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>