accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_pk>/', views.user_detail, name="user_detail"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name="delete"),
]

motube/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', views.index),
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name="detail"),
    path('<int:movie_pk>/review/', views.create_review, name="create_review"),
    path('<int:movie_pk>/review/delete/<int:review_pk>/', views.delete_review, name="delete_review"),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/score/<int:score>/', views.create_score, name='create_score'),
    path('search/', views.search, name='search'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

accounts/views.py
import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from movies.models import Movie, Movie_Score
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from movies.models import Review
from IPython import embed
from django_pandas.io import read_frame
import math

def sim_pearson(data, name1, name2):
    sumX=0 # X의 합
    sumY=0 # Y의 합
    sumPowX=0 # X 제곱의 합
    sumPowY=0 # Y 제곱의 합
    sumXY=0 # X*Y의 합
    count=0 #영화 개수
    if not data.get(name1):
        return 0
    for i in data[name1]: # i = key
        if math.isnan(data[name1][i]):
            continue
        if math.isnan(data[name2][i]):
            continue
        # name1, name2 둘 다 관심있는 영화
        sumX+=data[name1][i]
        sumY+=data[name2][i]
        sumPowX+=pow(data[name1][i],2)
        sumPowY+=pow(data[name2][i],2)
        sumXY+=data[name1][i]*data[name2][i]
        count+=1
    
    if count == 0:
        return 0
    a = sumXY- ((sumX*sumY)/count)
    b = (sumPowX - (pow(sumX,2) / count))
    c = (sumPowY - (pow(sumY,2) / count))
    d = math.sqrt(b * c)
    if d == 0:
        return 0
    return a / d

def top_match(data, name, index=3):
    li=[]
    for i in data: #딕셔너리를 돌고
        if name!=i: #자기 자신이 아닐때만
            li.append((sim_pearson(data,name,i),i)) #sim_function()을 통해 상관계수를 구하고 li[]에 추가
    li.sort() #오름차순
    li.reverse() #내림차순
    return li[:index]

def get_recommend(data, person):
    if not data.get(person):
        return []
    res = top_match(data, person)
    if not res:
        return []
    sim_person = max(res)[1]
    lst = []
    for movie in data[sim_person]:
        if math.isnan(data[sim_person][movie]):
            continue
        if math.isnan(data[person][movie]):
            lst.append(movie)

    return lst[:4]

# Create your views here.
def index(request):
    users = get_user_model().objects.all()
    context = {
        'users': users,
    }
    return render(request, 'accounts/index.html', context=context)

def user_detail(request, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    like_movies = person.like_movies.all()
    scores = Movie_Score.objects.all()
    if scores:
        ratings = scores.to_pivot_table(values='score', rows='movie', cols='user').to_dict()
        movie_names = get_recommend(ratings, request.user.username)
        movie_lst = []
        for name in movie_names:
            movie = Movie.objects.filter(title=name)[0]
            movie_lst.append(movie)
    else:
        movie_lst = []
    context = {
        'person': person,
        'like_movies': like_movies,
        "reco_movies": movie_lst
    }
    return render(request, 'accounts/detail.html', context=context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
        return redirect('accounts:login')
    else:
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/form.html', context=context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        return redirect('accounts:signup')
    else:
        form = CustomUserCreationForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/form.html', context=context)


@login_required
def delete(request):
    request.user.delete()
    return redirect("accounts:signup")

@login_required
def follow(request, person_pk):
    person = get_object_or_404(get_user_model(), pk=person_pk)
    if person.followers.filter(pk=request.user.pk).exists():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)

    return redirect("accounts:user_detail", person_pk)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="mt-3">
  {% if user.is_authenticated %}
  {% if user != person %}
  {% if user in person.followers.all %}
  <a href="{% url 'accounts:follow' person.pk %}">unfollow</a>
  {% else %}
  <a href="{% url 'accounts:follow' person.pk %}">follow</a>
  {% endif %}
  {% endif %}
  {% endif %}

  <h3 id="page_title" style="margin-top:30px; margin-bottom:20px;">찜한 영화</h3>
  <div class="row">
    {% for movie in like_movies %}
    <div class="col-3">
        <div class="card" style="width: 15rem;">
            <a href="{% url 'movies:detail' movie.pk %}"><img class="card-img-top" src="{{ movie.poster }}" alt="poster" style="height:20rem"></a>
        <div class="card-body px-3 py-3">
            <h5 class="card-title m-0"><a id="title_link" href="{% url 'movies:detail' movie.pk %}" style="font-size:1.1rem">{{ movie.title }}</a></h5>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>


    {% if reco_movies %}
      <h3 id="page_title" style="margin-top:30px; margin-bottom:20px;">이번엔 이거 볼까</h3>
    {% endif %}
    <div class="row">
    {% for movie in reco_movies %}
      <div class="col-3">
        <div class="card" style="width: 15rem;">
          <a href="{% url 'movies:detail' movie.pk %}"><img class="card-img-top" src="{{ movie.poster }}" alt="poster" style="height:20rem"></a>
          <div class="card-body px-3 py-3">
            <h5 class="card-title m-0"><a id="title_link" href="{% url 'movies:detail' movie.pk %}" style="font-size:1.1rem">{{ movie.title }}</a></h5>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
</div>

<style type="text/css">
  #title_link:link {
    color: black; text-decoration: none;
  }
  #title_link:visited {
    color: black; text-decoration: none;
  }
  #title_link:hover {
    color: black; text-decoration: none;
  }
  .card-title {
    text-align: center;
  }
  #page_title {
    color: #dcdcdc;
    font-family: 'Jua', sans-serif;
  }
  .card {
    background-color: #E0EBFF;
  }
  button {
    margin-left: 120px;
    margin-top: 10px;
  }
  #title_link {
    font-family: 'Black Han Sans', sans-serif;
  }
</style>
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <div class="">
      {% if request.resolver_match.url_name == 'signup' %}
        <h1 id="page_title">회원가입</h1>
      {% elif request.resolver_match.url_name == 'login' %}
        <h1 id="page_title">로그인</h1>
      {% endif %}    
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="제출">
      </form>
    </div>
  </div>
  <div class="col-3"></div>
</div>
<style>
    #page_title {
    color: #dcdcdc;
    font-family: 'Jua', sans-serif;
    margin-top:30px; 
    margin-bottom:20px;
  }
  label {
    color: #6C757D;
  }
</style>

{% endblock %}